version: "3.8"
services:

  db:
    image: postgres

    environment:
      POSTGRES_DB: database
      POSTGRES_USER: flo    
      POSTGRES_PASSWORD: password
      

  flaskapp:
    restart: always
    build: .
    
    
    ports:
      - "5000:5000"
    
    depends_on:
      - "db"
    
 